#!/usr/bin/env bash

function usage() {
    print_usage $(basename $0) "[--debug]"
    cat <<USAGE

Runs the blackbox recognizer, using tod kinect training dataset 9 and tod
kinect test dataset 27.  Might be useful for quick regression tests or also for
demonstration purposes.

--debug      if specified, starts in GNU debugger
USAGE
}

source $(rospack find clutseg)/../scripts/base.bash

cmd=""
if has_opt --debug ; then
    cmd="gdb --args"
fi

pushd $CLUTSEG_PATH > /dev/null
    $cmd $(rospack find clutseg)/bin/blackbox_recognizer \
        --base=tod_kinect_train_9/ \
        --tod_config=tod_kinect_train_9/config.yaml \
        --image=tod_kinect_test_27 \
        --testdesc=tod_kinect_test_27/testdesc-9.txt \
        --result=tod_kinect_test_27/blackbox_recognizer-demo.result.txt \
        --stats=tod_kinect_test_27/blackbox_recognizer-demo.stats.txt \
        --roc=tod_kinect_test_27/blackbox_recognizer-demo.roc.gnuplot \
        --verbose=1
popd > /dev/null

