#!/usr/bin/env bash
function usage() {
    print_usage $(basename $0) "testdesc"

    cat <<USAGE

Collects statistics for a test description file. Can check test description
file for typos, count the number of images, objects and the number of different
subjects seen on these images.

testdesc    a testdesc file

USAGE
}

source $(rospack find clutseg)/../scripts/base.bash

expect_arg 0

/usr/bin/env python $(rospack find clutseg)/scripts/testdesc-statistics.py "$@"
