#!/usr/bin/env bash
function usage() {
    print_usage
    cat <<EOF

Applies patches and modifications to dependencies through hardlinking.
EOF
}

cd $(rospack find clutseg)
source scripts/common

for mod in $(cat $CLUTSEG_PATH/clutter-segmentation/mods/mods.txt) ; do
    src=$CLUTSEG_PATH/clutter-segmentation/mods/$mod
    dst=$CLUTSEG_PATH/$mod 
    ln -v -f $src $dst
done

