#!/usr/bin/env bash

function usage() {
    print_usage $(basename $0) "semantic3d-base" "subject"
    
    cat <<USAGE

Shows all rotated, translated and delimitated point clouds of one training
subject in the semantic3d base.
USAGE
}

source $(rospack find clutseg)/scripts/common

expect_arg 0
expect_arg 1

base=$(get_arg 0)
obj=$(get_arg 1)

pushd $base/$obj.delimited.rotated.pcd > /dev/null
    rosrun pcl_visualization pcd_viewer \
        ${obj}_-180_.log.delimited.rotated.pcd \
        ${obj}_-150_.log.delimited.rotated.pcd \
        ${obj}_-120_.log.delimited.rotated.pcd \
        ${obj}_-90_.log.delimited.rotated.pcd \
        ${obj}_-60_.log.delimited.rotated.pcd \
        ${obj}_-30_.log.delimited.rotated.pcd \
        ${obj}_0_.log.delimited.rotated.pcd \
        ${obj}_30_.log.delimited.rotated.pcd \
        ${obj}_60_.log.delimited.rotated.pcd \
        ${obj}_90_.log.delimited.rotated.pcd \
        ${obj}_120_.log.delimited.rotated.pcd \
        ${obj}_150_.log.delimited.rotated.pcd \
        ${obj}_180_.log.delimited.rotated.pcd \
        -ax 0.2
popd > /dev/null
