#!/usr/bin/env bash

function usage() {
    print_usage $(basename $0) "semantic3d-base" "model" "angle"
    cat <<HELP

Displays the point clouds associated with a training subject from a certain
angle.

semantic3d-base     the directory where the data is in
model               display a view for this object 
angle               angle in 30 degrees step, use format \$04d 
HELP
}

source $(rospack find clutseg)/../scripts/base.bash

expect_arg 0
expect_arg 1
expect_arg 2

base=$(get_arg 0)
obj=$(get_arg 1)
angle=$(get_arg 2)

# workaround for bug https://code.ros.org/trac/wg-ros-pkg/ticket/5072
a=$(mktemp --suffix .pcd)
b=$(mktemp --suffix .pcd)
c=$(mktemp --suffix .pcd)

cp $CLUTSEG_PATH/semantic3d-data/$obj.delimited.rotated.pcd/${obj}_${angle}_.log.delimited.rotated.pcd $a
cp $CLUTSEG_PATH/semantic3d-data/$obj.delimited.pcd/${obj}_${angle}_.log.delimited.pcd $b
cp $CLUTSEG_PATH/semantic3d-data/$obj.pcd/${obj}_${angle}_.log.pcd $c

rosrun pcl_visualization pcd_viewer -fc 255,0,0 $a -fc 0,255,0 $b -f 0,0,255 $c -ax 0.1 

rm $a
rm $b
rm $c
