#!/usr/bin/env bash

function usage() {
    print_usage $(basename $0) "[gtest_filter]" "[--fast]"

    cat <<USAGE

Tests clutseg. Better than 'make tests' because it does not rebuild the
executables.  Only useful in quick edit-compile-test cycles.

gtest_filter    the Google Test filter as accepted by --gtest_filter option
--fast          if set, tests that take more time are skipped
USAGE
}

cd $(rospack find clutseg)
source scripts/common

cp CMakeLists.txt CMakeLists.txt.backup
cp CMakeListsTest.txt CMakeLists.txt

make tests -j 4
if [ "$?" = "0" ] ; then
    if has_opt "--fast" ; then
        touch build/fast.flag
    fi
    
    f=$(get_arg 0)
    if [ "$f" = "" ] ; then
       ./bin/utest
    else
       ./bin/utest --gtest_filter=$f
    fi

    if has_opt "--fast" ; then
        rm build/fast.flag
    fi
fi

mv CMakeLists.txt.backup CMakeLists.txt

