#!/usr/bin/env bash

function usage() {
    print_usage $(basename $0)
    cat <<USAGE

Runs the "recognizer" executable of tod_detecting in the GNU debugger, filling
in all the required arguments and options.
USAGE
}

source $(rospack find clutseg)/../scripts/base.bash

pkg_tod_detecting=$(rospack find tod_detecting)
gdb --args $pkg_tod_detecting/bin/recognizer \
    --base=$CLUTSEG_PATH/tod_kinect_train_9 \
    --image=$CLUTSEG_PATH/tod_kinect_train_9/fat_free_milk/image_00000.png \
    --tod_config=$CLUTSEG_PATH/tod_kinect_train_9/config.yaml \
    --verbose=1 \
    --mode=1

