#!/usr/bin/env bash

function usage() {
    print_usage "train-detect" "training-base" "[--verbose]" "[--serial]" "[--debug]"
    cat <<USAGE

Detects features from training images given poses and masks.

--verbose       be talkative
--serial        do not use multiple threads; for paranoid people
--debug         run the feature detection in GNU debugger
USAGE
}

source $(rospack find clutseg)/../scripts/base.bash

expect_arg 0
base=$(get_arg 0)

if has_opt --verbose ; then
    verbose="--verbose=1"
fi

if has_opt --debug ; then
    debug="gdb --args "
fi

jobs=8
if has_opt --serial ; then
    jobs=1
fi

pushd $base > /dev/null
    assert_base
    for d in *; do
        if [ -d $d ]; then
            subj=$(basename $d)
            echo "Extract features for $subj"
            echo "--------------------------------------------------------"
            echo "Running tod_training detector ..."
            $debug $(rospack find tod_training)/bin/detector -d $subj -j$jobs $verbose
        fi
    done
popd > /dev/null

