#!/usr/bin/env bash

function usage() {
    print_usage "training-base"
    cat <<USAGE

Maps 2D keypoints to their corresponding 3D points in training image.
USAGE
}

source $(rospack find clutseg)/scripts/common

expect_arg 0
base=$(get_arg 0)

pushd $base > /dev/null
    assert_base
    for d in *; do
        if [ -d $d ]; then
            subj=$(basename $d)
            echo "Mapping 2d-3d: $subj"
            echo "--------------------------------------------------------"
            echo "Running tod_training f3d_creator ..."
            rosrun tod_training f3d_creator -d $subj -j8
        fi
    done
popd > /dev/null

