\section{Textured Object Detection Library}
%\subsection{Solutions in Perceptions Challenge 2011}
\subsection{Learning}
\label{subsection:learning},

\subsection{Recognition}
\label{subsection:recognition}

\section{Clutter Segmentation Tool}
\subsection{Guess Ranking}
\subsection{Guess Rejection}
\subsection{Guess Refinement}

\section{Parameter Optimization}
\subsection{Parameter Space}
\subsection{Measured Statistics}
\subsection{Experiment Strategy}
\subsection{Experiment Runner}

